package winkhouse.model.winkcloud;

public enum CloudQueryOrigin {
	SEARCH_IMMOBILI, 
	SEARCH_ANAGRAFICHE,
	CORE_TIPIIMMOBILI,
	CORE_CLASSIENERGETICHE,
	CORE_CLASSICLIENTI,
	CORE_TIPICOLLOQUI,
	CORE_TIPISTANZE,
	CORE_TIPICONTATTI,
	CORE_RISCALDAMENTI,
	CORE_STATOCONSERVATIVO,
	GET_COLLOQUI_IMMOBILE,
	GET_COLLOQUI_ANAGRAFICA,
	GET_ABBINAMENTI_ANAGRAFICHE_IMMOBILE,
	GET_ABBINAMENTI_IMMOBILI_ANAGRAFICA,
	POST_PUT_IMMOBILE,
	POST_PUT_ANAGRAFICA,
	POST_PUT_COLLOQUI,
	POST_PUT_IMMAGINI,
}
