package winkhouse.model.winkcloud.mobilecolumns;

public interface ImmobiliColumnNames {
	
	String CODIMMOBILE = "CODIMMOBILE";
	String RIF="RIF";
	String INDIRIZZO="INDIRIZZO";
	String PROVINCIA="PROVINCIA";
	String CAP="CAP";
	String CITTA="CITTA";
	String ZONA="ZONA";
	String DATAINSERIMENTO="DATAINSERIMENTO";
	String DATALIBERO="DATALIBERO";
	String DESCRIZIONE="DESCRIZIONE";
	String MUTUODESCRIZIONE="MUTUODESCRIZIONE";
	String PREZZO="PREZZO";
	String MUTUO="MUTUO";
	String SPESE="SPESE";
	String VARIE="VARIE";
	String VISIONE="VISIONE";
	String STORICO="STORICO";
	String AFFITTO="AFFITTO";
	String MQ="MQ";
	String ANNOCOSTRUZIONE="ANNOCOSTRUZIONE";
	String CODAGENTEINSERITORE="CODAGENTEINSERITORE";
	String CODANAGRAFICA="CODANAGRAFICA";
	String CODRISCALDAMENTO="CODRISCALDAMENTO";
	String CODSTATO="CODSTATO";
	String CODTIPOLOGIA="CODTIPOLOGIA";
	String CODCLASSEENERGETICA="CODCLASSEENERGETICA";

}
