package winkhouse.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import winkhouse.orm.Agenti;
import winkhouse.orm.Anagrafiche;
import winkhouse.orm.Immobili;

/**
 * Class _Abbinamenti was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Abbinamenti extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODABBINAMENTO_PK_COLUMN = "CODABBINAMENTO";

    public static final Property<LocalDateTime> DATEUPDATE = Property.create("dateupdate", LocalDateTime.class);
    public static final Property<Agenti> AGENTI = Property.create("agenti", Agenti.class);
    public static final Property<Anagrafiche> ANAGRAFICHE = Property.create("anagrafiche", Anagrafiche.class);
    public static final Property<Immobili> IMMOBILI = Property.create("immobili", Immobili.class);

    protected LocalDateTime dateupdate;

    protected Object agenti;
    protected Object anagrafiche;
    protected Object immobili;

    public void setDateupdate(LocalDateTime dateupdate) {
        beforePropertyWrite("dateupdate", this.dateupdate, dateupdate);
        this.dateupdate = dateupdate;
    }

    public LocalDateTime getDateupdate() {
        beforePropertyRead("dateupdate");
        return this.dateupdate;
    }

    public void setAgenti(Agenti agenti) {
        setToOneTarget("agenti", agenti, true);
    }

    public Agenti getAgenti() {
        return (Agenti)readProperty("agenti");
    }

    public void setAnagrafiche(Anagrafiche anagrafiche) {
        setToOneTarget("anagrafiche", anagrafiche, true);
    }

    public Anagrafiche getAnagrafiche() {
        return (Anagrafiche)readProperty("anagrafiche");
    }

    public void setImmobili(Immobili immobili) {
        setToOneTarget("immobili", immobili, true);
    }

    public Immobili getImmobili() {
        return (Immobili)readProperty("immobili");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "dateupdate":
                return this.dateupdate;
            case "agenti":
                return this.agenti;
            case "anagrafiche":
                return this.anagrafiche;
            case "immobili":
                return this.immobili;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "dateupdate":
                this.dateupdate = (LocalDateTime)val;
                break;
            case "agenti":
                this.agenti = val;
                break;
            case "anagrafiche":
                this.anagrafiche = val;
                break;
            case "immobili":
                this.immobili = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.dateupdate);
        out.writeObject(this.agenti);
        out.writeObject(this.anagrafiche);
        out.writeObject(this.immobili);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.dateupdate = (LocalDateTime)in.readObject();
        this.agenti = in.readObject();
        this.anagrafiche = in.readObject();
        this.immobili = in.readObject();
    }

}
