package winkhouse.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import winkhouse.orm.Affitti;
import winkhouse.orm.Agenti;

/**
 * Class _Affittiallegati was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Affittiallegati extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODAFFITTIALLEGATI_PK_COLUMN = "CODAFFITTIALLEGATI";

    public static final Property<LocalDateTime> DATEUPDATE = Property.create("dateupdate", LocalDateTime.class);
    public static final Property<String> DESCRIZIONE = Property.create("descrizione", String.class);
    public static final Property<String> NOME = Property.create("nome", String.class);
    public static final Property<Affitti> AFFITTI = Property.create("affitti", Affitti.class);
    public static final Property<Agenti> AGENTI = Property.create("agenti", Agenti.class);

    protected LocalDateTime dateupdate;
    protected String descrizione;
    protected String nome;

    protected Object affitti;
    protected Object agenti;

    public void setDateupdate(LocalDateTime dateupdate) {
        beforePropertyWrite("dateupdate", this.dateupdate, dateupdate);
        this.dateupdate = dateupdate;
    }

    public LocalDateTime getDateupdate() {
        beforePropertyRead("dateupdate");
        return this.dateupdate;
    }

    public void setDescrizione(String descrizione) {
        beforePropertyWrite("descrizione", this.descrizione, descrizione);
        this.descrizione = descrizione;
    }

    public String getDescrizione() {
        beforePropertyRead("descrizione");
        return this.descrizione;
    }

    public void setNome(String nome) {
        beforePropertyWrite("nome", this.nome, nome);
        this.nome = nome;
    }

    public String getNome() {
        beforePropertyRead("nome");
        return this.nome;
    }

    public void setAffitti(Affitti affitti) {
        setToOneTarget("affitti", affitti, true);
    }

    public Affitti getAffitti() {
        return (Affitti)readProperty("affitti");
    }

    public void setAgenti(Agenti agenti) {
        setToOneTarget("agenti", agenti, true);
    }

    public Agenti getAgenti() {
        return (Agenti)readProperty("agenti");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "dateupdate":
                return this.dateupdate;
            case "descrizione":
                return this.descrizione;
            case "nome":
                return this.nome;
            case "affitti":
                return this.affitti;
            case "agenti":
                return this.agenti;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "dateupdate":
                this.dateupdate = (LocalDateTime)val;
                break;
            case "descrizione":
                this.descrizione = (String)val;
                break;
            case "nome":
                this.nome = (String)val;
                break;
            case "affitti":
                this.affitti = val;
                break;
            case "agenti":
                this.agenti = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.dateupdate);
        out.writeObject(this.descrizione);
        out.writeObject(this.nome);
        out.writeObject(this.affitti);
        out.writeObject(this.agenti);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.dateupdate = (LocalDateTime)in.readObject();
        this.descrizione = (String)in.readObject();
        this.nome = (String)in.readObject();
        this.affitti = in.readObject();
        this.agenti = in.readObject();
    }

}
