package winkhouse.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import winkhouse.orm.Affitti;
import winkhouse.orm.Agenti;
import winkhouse.orm.Anagrafiche;

/**
 * Class _Affittianagrafiche was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Affittianagrafiche extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODAFFITTIANAGRAFICHE_PK_COLUMN = "CODAFFITTIANAGRAFICHE";

    public static final Property<LocalDateTime> DATEUPDATE = Property.create("dateupdate", LocalDateTime.class);
    public static final Property<String> NOTA = Property.create("nota", String.class);
    public static final Property<Affitti> AFFITTI = Property.create("affitti", Affitti.class);
    public static final Property<Agenti> AGENTI = Property.create("agenti", Agenti.class);
    public static final Property<Anagrafiche> ANAGRAFICHE = Property.create("anagrafiche", Anagrafiche.class);

    protected LocalDateTime dateupdate;
    protected String nota;

    protected Object affitti;
    protected Object agenti;
    protected Object anagrafiche;

    public void setDateupdate(LocalDateTime dateupdate) {
        beforePropertyWrite("dateupdate", this.dateupdate, dateupdate);
        this.dateupdate = dateupdate;
    }

    public LocalDateTime getDateupdate() {
        beforePropertyRead("dateupdate");
        return this.dateupdate;
    }

    public void setNota(String nota) {
        beforePropertyWrite("nota", this.nota, nota);
        this.nota = nota;
    }

    public String getNota() {
        beforePropertyRead("nota");
        return this.nota;
    }

    public void setAffitti(Affitti affitti) {
        setToOneTarget("affitti", affitti, true);
    }

    public Affitti getAffitti() {
        return (Affitti)readProperty("affitti");
    }

    public void setAgenti(Agenti agenti) {
        setToOneTarget("agenti", agenti, true);
    }

    public Agenti getAgenti() {
        return (Agenti)readProperty("agenti");
    }

    public void setAnagrafiche(Anagrafiche anagrafiche) {
        setToOneTarget("anagrafiche", anagrafiche, true);
    }

    public Anagrafiche getAnagrafiche() {
        return (Anagrafiche)readProperty("anagrafiche");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "dateupdate":
                return this.dateupdate;
            case "nota":
                return this.nota;
            case "affitti":
                return this.affitti;
            case "agenti":
                return this.agenti;
            case "anagrafiche":
                return this.anagrafiche;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "dateupdate":
                this.dateupdate = (LocalDateTime)val;
                break;
            case "nota":
                this.nota = (String)val;
                break;
            case "affitti":
                this.affitti = val;
                break;
            case "agenti":
                this.agenti = val;
                break;
            case "anagrafiche":
                this.anagrafiche = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.dateupdate);
        out.writeObject(this.nota);
        out.writeObject(this.affitti);
        out.writeObject(this.agenti);
        out.writeObject(this.anagrafiche);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.dateupdate = (LocalDateTime)in.readObject();
        this.nota = (String)in.readObject();
        this.affitti = in.readObject();
        this.agenti = in.readObject();
        this.anagrafiche = in.readObject();
    }

}
