package winkhouse.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import winkhouse.orm.Affitti;
import winkhouse.orm.Affittirate;
import winkhouse.orm.Agenti;
import winkhouse.orm.Anagrafiche;

/**
 * Class _Affittirate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Affittirate extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODAFFITTIRATE_PK_COLUMN = "CODAFFITTIRATE";

    public static final Property<LocalDateTime> DATAPAGATO = Property.create("datapagato", LocalDateTime.class);
    public static final Property<LocalDateTime> DATEUPDATE = Property.create("dateupdate", LocalDateTime.class);
    public static final Property<Double> IMPORTO = Property.create("importo", Double.class);
    public static final Property<Integer> MESE = Property.create("mese", Integer.class);
    public static final Property<String> NOTA = Property.create("nota", String.class);
    public static final Property<LocalDateTime> SCADENZA = Property.create("scadenza", LocalDateTime.class);
    public static final Property<Affitti> AFFITTI = Property.create("affitti", Affitti.class);
    public static final Property<Affittirate> AFFITTIRATE = Property.create("affittirate", Affittirate.class);
    public static final Property<List<Affittirate>> AFFITTIRATES = Property.create("affittirates", List.class);
    public static final Property<Agenti> AGENTI = Property.create("agenti", Agenti.class);
    public static final Property<Anagrafiche> ANAGRAFICHE = Property.create("anagrafiche", Anagrafiche.class);

    protected LocalDateTime datapagato;
    protected LocalDateTime dateupdate;
    protected Double importo;
    protected Integer mese;
    protected String nota;
    protected LocalDateTime scadenza;

    protected Object affitti;
    protected Object affittirate;
    protected Object affittirates;
    protected Object agenti;
    protected Object anagrafiche;

    public void setDatapagato(LocalDateTime datapagato) {
        beforePropertyWrite("datapagato", this.datapagato, datapagato);
        this.datapagato = datapagato;
    }

    public LocalDateTime getDatapagato() {
        beforePropertyRead("datapagato");
        return this.datapagato;
    }

    public void setDateupdate(LocalDateTime dateupdate) {
        beforePropertyWrite("dateupdate", this.dateupdate, dateupdate);
        this.dateupdate = dateupdate;
    }

    public LocalDateTime getDateupdate() {
        beforePropertyRead("dateupdate");
        return this.dateupdate;
    }

    public void setImporto(double importo) {
        beforePropertyWrite("importo", this.importo, importo);
        this.importo = importo;
    }

    public double getImporto() {
        beforePropertyRead("importo");
        if(this.importo == null) {
            return 0;
        }
        return this.importo;
    }

    public void setMese(int mese) {
        beforePropertyWrite("mese", this.mese, mese);
        this.mese = mese;
    }

    public int getMese() {
        beforePropertyRead("mese");
        if(this.mese == null) {
            return 0;
        }
        return this.mese;
    }

    public void setNota(String nota) {
        beforePropertyWrite("nota", this.nota, nota);
        this.nota = nota;
    }

    public String getNota() {
        beforePropertyRead("nota");
        return this.nota;
    }

    public void setScadenza(LocalDateTime scadenza) {
        beforePropertyWrite("scadenza", this.scadenza, scadenza);
        this.scadenza = scadenza;
    }

    public LocalDateTime getScadenza() {
        beforePropertyRead("scadenza");
        return this.scadenza;
    }

    public void setAffitti(Affitti affitti) {
        setToOneTarget("affitti", affitti, true);
    }

    public Affitti getAffitti() {
        return (Affitti)readProperty("affitti");
    }

    public void setAffittirate(Affittirate affittirate) {
        setToOneTarget("affittirate", affittirate, true);
    }

    public Affittirate getAffittirate() {
        return (Affittirate)readProperty("affittirate");
    }

    public void addToAffittirates(Affittirate obj) {
        addToManyTarget("affittirates", obj, true);
    }

    public void removeFromAffittirates(Affittirate obj) {
        removeToManyTarget("affittirates", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Affittirate> getAffittirates() {
        return (List<Affittirate>)readProperty("affittirates");
    }

    public void setAgenti(Agenti agenti) {
        setToOneTarget("agenti", agenti, true);
    }

    public Agenti getAgenti() {
        return (Agenti)readProperty("agenti");
    }

    public void setAnagrafiche(Anagrafiche anagrafiche) {
        setToOneTarget("anagrafiche", anagrafiche, true);
    }

    public Anagrafiche getAnagrafiche() {
        return (Anagrafiche)readProperty("anagrafiche");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "datapagato":
                return this.datapagato;
            case "dateupdate":
                return this.dateupdate;
            case "importo":
                return this.importo;
            case "mese":
                return this.mese;
            case "nota":
                return this.nota;
            case "scadenza":
                return this.scadenza;
            case "affitti":
                return this.affitti;
            case "affittirate":
                return this.affittirate;
            case "affittirates":
                return this.affittirates;
            case "agenti":
                return this.agenti;
            case "anagrafiche":
                return this.anagrafiche;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "datapagato":
                this.datapagato = (LocalDateTime)val;
                break;
            case "dateupdate":
                this.dateupdate = (LocalDateTime)val;
                break;
            case "importo":
                this.importo = (Double)val;
                break;
            case "mese":
                this.mese = (Integer)val;
                break;
            case "nota":
                this.nota = (String)val;
                break;
            case "scadenza":
                this.scadenza = (LocalDateTime)val;
                break;
            case "affitti":
                this.affitti = val;
                break;
            case "affittirate":
                this.affittirate = val;
                break;
            case "affittirates":
                this.affittirates = val;
                break;
            case "agenti":
                this.agenti = val;
                break;
            case "anagrafiche":
                this.anagrafiche = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.datapagato);
        out.writeObject(this.dateupdate);
        out.writeObject(this.importo);
        out.writeObject(this.mese);
        out.writeObject(this.nota);
        out.writeObject(this.scadenza);
        out.writeObject(this.affitti);
        out.writeObject(this.affittirate);
        out.writeObject(this.affittirates);
        out.writeObject(this.agenti);
        out.writeObject(this.anagrafiche);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.datapagato = (LocalDateTime)in.readObject();
        this.dateupdate = (LocalDateTime)in.readObject();
        this.importo = (Double)in.readObject();
        this.mese = (Integer)in.readObject();
        this.nota = (String)in.readObject();
        this.scadenza = (LocalDateTime)in.readObject();
        this.affitti = in.readObject();
        this.affittirate = in.readObject();
        this.affittirates = in.readObject();
        this.agenti = in.readObject();
        this.anagrafiche = in.readObject();
    }

}
