package winkhouse.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import winkhouse.orm.Agenti;
import winkhouse.orm.Colloqui;

/**
 * Class _Allegaticolloquio was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Allegaticolloquio extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODALLEGATICOLLOQUIO_PK_COLUMN = "CODALLEGATICOLLOQUIO";

    public static final Property<String> COMMENTO = Property.create("commento", String.class);
    public static final Property<LocalDateTime> DATEUPDATE = Property.create("dateupdate", LocalDateTime.class);
    public static final Property<String> NOME = Property.create("nome", String.class);
    public static final Property<Agenti> AGENTI = Property.create("agenti", Agenti.class);
    public static final Property<Colloqui> COLLOQUI = Property.create("colloqui", Colloqui.class);

    protected String commento;
    protected LocalDateTime dateupdate;
    protected String nome;

    protected Object agenti;
    protected Object colloqui;

    public void setCommento(String commento) {
        beforePropertyWrite("commento", this.commento, commento);
        this.commento = commento;
    }

    public String getCommento() {
        beforePropertyRead("commento");
        return this.commento;
    }

    public void setDateupdate(LocalDateTime dateupdate) {
        beforePropertyWrite("dateupdate", this.dateupdate, dateupdate);
        this.dateupdate = dateupdate;
    }

    public LocalDateTime getDateupdate() {
        beforePropertyRead("dateupdate");
        return this.dateupdate;
    }

    public void setNome(String nome) {
        beforePropertyWrite("nome", this.nome, nome);
        this.nome = nome;
    }

    public String getNome() {
        beforePropertyRead("nome");
        return this.nome;
    }

    public void setAgenti(Agenti agenti) {
        setToOneTarget("agenti", agenti, true);
    }

    public Agenti getAgenti() {
        return (Agenti)readProperty("agenti");
    }

    public void setColloqui(Colloqui colloqui) {
        setToOneTarget("colloqui", colloqui, true);
    }

    public Colloqui getColloqui() {
        return (Colloqui)readProperty("colloqui");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "commento":
                return this.commento;
            case "dateupdate":
                return this.dateupdate;
            case "nome":
                return this.nome;
            case "agenti":
                return this.agenti;
            case "colloqui":
                return this.colloqui;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "commento":
                this.commento = (String)val;
                break;
            case "dateupdate":
                this.dateupdate = (LocalDateTime)val;
                break;
            case "nome":
                this.nome = (String)val;
                break;
            case "agenti":
                this.agenti = val;
                break;
            case "colloqui":
                this.colloqui = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.commento);
        out.writeObject(this.dateupdate);
        out.writeObject(this.nome);
        out.writeObject(this.agenti);
        out.writeObject(this.colloqui);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.commento = (String)in.readObject();
        this.dateupdate = (LocalDateTime)in.readObject();
        this.nome = (String)in.readObject();
        this.agenti = in.readObject();
        this.colloqui = in.readObject();
    }

}
