package winkhouse.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import winkhouse.orm.Agenti;
import winkhouse.orm.Anagrafiche;
import winkhouse.orm.Appuntamenti;

/**
 * Class _Anagraficheappuntamenti was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Anagraficheappuntamenti extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODANAGRAFICHEAPPUNTAMENTI_PK_COLUMN = "CODANAGRAFICHEAPPUNTAMENTI";

    public static final Property<LocalDateTime> DATEUPDATE = Property.create("dateupdate", LocalDateTime.class);
    public static final Property<String> NOTE = Property.create("note", String.class);
    public static final Property<Agenti> AGENTI = Property.create("agenti", Agenti.class);
    public static final Property<Anagrafiche> ANAGRAFICHE = Property.create("anagrafiche", Anagrafiche.class);
    public static final Property<Appuntamenti> APPUNTAMENTI = Property.create("appuntamenti", Appuntamenti.class);

    protected LocalDateTime dateupdate;
    protected String note;

    protected Object agenti;
    protected Object anagrafiche;
    protected Object appuntamenti;

    public void setDateupdate(LocalDateTime dateupdate) {
        beforePropertyWrite("dateupdate", this.dateupdate, dateupdate);
        this.dateupdate = dateupdate;
    }

    public LocalDateTime getDateupdate() {
        beforePropertyRead("dateupdate");
        return this.dateupdate;
    }

    public void setNote(String note) {
        beforePropertyWrite("note", this.note, note);
        this.note = note;
    }

    public String getNote() {
        beforePropertyRead("note");
        return this.note;
    }

    public void setAgenti(Agenti agenti) {
        setToOneTarget("agenti", agenti, true);
    }

    public Agenti getAgenti() {
        return (Agenti)readProperty("agenti");
    }

    public void setAnagrafiche(Anagrafiche anagrafiche) {
        setToOneTarget("anagrafiche", anagrafiche, true);
    }

    public Anagrafiche getAnagrafiche() {
        return (Anagrafiche)readProperty("anagrafiche");
    }

    public void setAppuntamenti(Appuntamenti appuntamenti) {
        setToOneTarget("appuntamenti", appuntamenti, true);
    }

    public Appuntamenti getAppuntamenti() {
        return (Appuntamenti)readProperty("appuntamenti");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "dateupdate":
                return this.dateupdate;
            case "note":
                return this.note;
            case "agenti":
                return this.agenti;
            case "anagrafiche":
                return this.anagrafiche;
            case "appuntamenti":
                return this.appuntamenti;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "dateupdate":
                this.dateupdate = (LocalDateTime)val;
                break;
            case "note":
                this.note = (String)val;
                break;
            case "agenti":
                this.agenti = val;
                break;
            case "anagrafiche":
                this.anagrafiche = val;
                break;
            case "appuntamenti":
                this.appuntamenti = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.dateupdate);
        out.writeObject(this.note);
        out.writeObject(this.agenti);
        out.writeObject(this.anagrafiche);
        out.writeObject(this.appuntamenti);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.dateupdate = (LocalDateTime)in.readObject();
        this.note = (String)in.readObject();
        this.agenti = in.readObject();
        this.anagrafiche = in.readObject();
        this.appuntamenti = in.readObject();
    }

}
