package winkhouse.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import winkhouse.orm.Agenti;

/**
 * Class _Colloquiagenti was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Colloquiagenti extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODCOLLOQUIOAGENTE_PK_COLUMN = "CODCOLLOQUIOAGENTE";

    public static final Property<Integer> CODCOLLOQUIO = Property.create("codcolloquio", Integer.class);
    public static final Property<String> COMMENTO = Property.create("commento", String.class);
    public static final Property<LocalDateTime> DATEUPDATE = Property.create("dateupdate", LocalDateTime.class);
    public static final Property<Agenti> AGENTI = Property.create("agenti", Agenti.class);
    public static final Property<Agenti> AGENTI1 = Property.create("agenti1", Agenti.class);

    protected Integer codcolloquio;
    protected String commento;
    protected LocalDateTime dateupdate;

    protected Object agenti;
    protected Object agenti1;

    public void setCodcolloquio(int codcolloquio) {
        beforePropertyWrite("codcolloquio", this.codcolloquio, codcolloquio);
        this.codcolloquio = codcolloquio;
    }

    public int getCodcolloquio() {
        beforePropertyRead("codcolloquio");
        if(this.codcolloquio == null) {
            return 0;
        }
        return this.codcolloquio;
    }

    public void setCommento(String commento) {
        beforePropertyWrite("commento", this.commento, commento);
        this.commento = commento;
    }

    public String getCommento() {
        beforePropertyRead("commento");
        return this.commento;
    }

    public void setDateupdate(LocalDateTime dateupdate) {
        beforePropertyWrite("dateupdate", this.dateupdate, dateupdate);
        this.dateupdate = dateupdate;
    }

    public LocalDateTime getDateupdate() {
        beforePropertyRead("dateupdate");
        return this.dateupdate;
    }

    public void setAgenti(Agenti agenti) {
        setToOneTarget("agenti", agenti, true);
    }

    public Agenti getAgenti() {
        return (Agenti)readProperty("agenti");
    }

    public void setAgenti1(Agenti agenti1) {
        setToOneTarget("agenti1", agenti1, true);
    }

    public Agenti getAgenti1() {
        return (Agenti)readProperty("agenti1");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "codcolloquio":
                return this.codcolloquio;
            case "commento":
                return this.commento;
            case "dateupdate":
                return this.dateupdate;
            case "agenti":
                return this.agenti;
            case "agenti1":
                return this.agenti1;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "codcolloquio":
                this.codcolloquio = (Integer)val;
                break;
            case "commento":
                this.commento = (String)val;
                break;
            case "dateupdate":
                this.dateupdate = (LocalDateTime)val;
                break;
            case "agenti":
                this.agenti = val;
                break;
            case "agenti1":
                this.agenti1 = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.codcolloquio);
        out.writeObject(this.commento);
        out.writeObject(this.dateupdate);
        out.writeObject(this.agenti);
        out.writeObject(this.agenti1);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.codcolloquio = (Integer)in.readObject();
        this.commento = (String)in.readObject();
        this.dateupdate = (LocalDateTime)in.readObject();
        this.agenti = in.readObject();
        this.agenti1 = in.readObject();
    }

}
