package winkhouse.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import winkhouse.orm.Agenti;
import winkhouse.orm.Anagrafiche;
import winkhouse.orm.Gdata;
import winkhouse.orm.Tipologiecontatti;

/**
 * Class _Contatti was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contatti extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODCONTATTO_PK_COLUMN = "CODCONTATTO";

    public static final Property<String> CONTATTO = Property.create("contatto", String.class);
    public static final Property<LocalDateTime> DATEUPDATE = Property.create("dateupdate", LocalDateTime.class);
    public static final Property<String> DESCRIZIONE = Property.create("descrizione", String.class);
    public static final Property<Agenti> AGENTI = Property.create("agenti", Agenti.class);
    public static final Property<Agenti> AGENTI1 = Property.create("agenti1", Agenti.class);
    public static final Property<Anagrafiche> ANAGRAFICHE = Property.create("anagrafiche", Anagrafiche.class);
    public static final Property<List<Gdata>> GDATAS = Property.create("gdatas", List.class);
    public static final Property<Tipologiecontatti> TIPOLOGIECONTATTI = Property.create("tipologiecontatti", Tipologiecontatti.class);

    protected String contatto;
    protected LocalDateTime dateupdate;
    protected String descrizione;

    protected Object agenti;
    protected Object agenti1;
    protected Object anagrafiche;
    protected Object gdatas;
    protected Object tipologiecontatti;

    public void setContatto(String contatto) {
        beforePropertyWrite("contatto", this.contatto, contatto);
        this.contatto = contatto;
    }

    public String getContatto() {
        beforePropertyRead("contatto");
        return this.contatto;
    }

    public void setDateupdate(LocalDateTime dateupdate) {
        beforePropertyWrite("dateupdate", this.dateupdate, dateupdate);
        this.dateupdate = dateupdate;
    }

    public LocalDateTime getDateupdate() {
        beforePropertyRead("dateupdate");
        return this.dateupdate;
    }

    public void setDescrizione(String descrizione) {
        beforePropertyWrite("descrizione", this.descrizione, descrizione);
        this.descrizione = descrizione;
    }

    public String getDescrizione() {
        beforePropertyRead("descrizione");
        return this.descrizione;
    }

    public void setAgenti(Agenti agenti) {
        setToOneTarget("agenti", agenti, true);
    }

    public Agenti getAgenti() {
        return (Agenti)readProperty("agenti");
    }

    public void setAgenti1(Agenti agenti1) {
        setToOneTarget("agenti1", agenti1, true);
    }

    public Agenti getAgenti1() {
        return (Agenti)readProperty("agenti1");
    }

    public void setAnagrafiche(Anagrafiche anagrafiche) {
        setToOneTarget("anagrafiche", anagrafiche, true);
    }

    public Anagrafiche getAnagrafiche() {
        return (Anagrafiche)readProperty("anagrafiche");
    }

    public void addToGdatas(Gdata obj) {
        addToManyTarget("gdatas", obj, true);
    }

    public void removeFromGdatas(Gdata obj) {
        removeToManyTarget("gdatas", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Gdata> getGdatas() {
        return (List<Gdata>)readProperty("gdatas");
    }

    public void setTipologiecontatti(Tipologiecontatti tipologiecontatti) {
        setToOneTarget("tipologiecontatti", tipologiecontatti, true);
    }

    public Tipologiecontatti getTipologiecontatti() {
        return (Tipologiecontatti)readProperty("tipologiecontatti");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "contatto":
                return this.contatto;
            case "dateupdate":
                return this.dateupdate;
            case "descrizione":
                return this.descrizione;
            case "agenti":
                return this.agenti;
            case "agenti1":
                return this.agenti1;
            case "anagrafiche":
                return this.anagrafiche;
            case "gdatas":
                return this.gdatas;
            case "tipologiecontatti":
                return this.tipologiecontatti;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "contatto":
                this.contatto = (String)val;
                break;
            case "dateupdate":
                this.dateupdate = (LocalDateTime)val;
                break;
            case "descrizione":
                this.descrizione = (String)val;
                break;
            case "agenti":
                this.agenti = val;
                break;
            case "agenti1":
                this.agenti1 = val;
                break;
            case "anagrafiche":
                this.anagrafiche = val;
                break;
            case "gdatas":
                this.gdatas = val;
                break;
            case "tipologiecontatti":
                this.tipologiecontatti = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.contatto);
        out.writeObject(this.dateupdate);
        out.writeObject(this.descrizione);
        out.writeObject(this.agenti);
        out.writeObject(this.agenti1);
        out.writeObject(this.anagrafiche);
        out.writeObject(this.gdatas);
        out.writeObject(this.tipologiecontatti);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.contatto = (String)in.readObject();
        this.dateupdate = (LocalDateTime)in.readObject();
        this.descrizione = (String)in.readObject();
        this.agenti = in.readObject();
        this.agenti1 = in.readObject();
        this.anagrafiche = in.readObject();
        this.gdatas = in.readObject();
        this.tipologiecontatti = in.readObject();
    }

}
