package winkhouse.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import winkhouse.orm.Agenti;
import winkhouse.orm.Contatti;
import winkhouse.orm.Gcalendar;

/**
 * Class _Gdata was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Gdata extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODGDATA_PK_COLUMN = "CODGDATA";

    public static final Property<LocalDateTime> DATEUPDATE = Property.create("dateupdate", LocalDateTime.class);
    public static final Property<String> DESCRIZIONE = Property.create("descrizione", String.class);
    public static final Property<String> PWSKEY = Property.create("pwskey", String.class);
    public static final Property<Agenti> AGENTI = Property.create("agenti", Agenti.class);
    public static final Property<Contatti> CONTATTI = Property.create("contatti", Contatti.class);
    public static final Property<List<Gcalendar>> GCALENDARS = Property.create("gcalendars", List.class);

    protected LocalDateTime dateupdate;
    protected String descrizione;
    protected String pwskey;

    protected Object agenti;
    protected Object contatti;
    protected Object gcalendars;

    public void setDateupdate(LocalDateTime dateupdate) {
        beforePropertyWrite("dateupdate", this.dateupdate, dateupdate);
        this.dateupdate = dateupdate;
    }

    public LocalDateTime getDateupdate() {
        beforePropertyRead("dateupdate");
        return this.dateupdate;
    }

    public void setDescrizione(String descrizione) {
        beforePropertyWrite("descrizione", this.descrizione, descrizione);
        this.descrizione = descrizione;
    }

    public String getDescrizione() {
        beforePropertyRead("descrizione");
        return this.descrizione;
    }

    public void setPwskey(String pwskey) {
        beforePropertyWrite("pwskey", this.pwskey, pwskey);
        this.pwskey = pwskey;
    }

    public String getPwskey() {
        beforePropertyRead("pwskey");
        return this.pwskey;
    }

    public void setAgenti(Agenti agenti) {
        setToOneTarget("agenti", agenti, true);
    }

    public Agenti getAgenti() {
        return (Agenti)readProperty("agenti");
    }

    public void setContatti(Contatti contatti) {
        setToOneTarget("contatti", contatti, true);
    }

    public Contatti getContatti() {
        return (Contatti)readProperty("contatti");
    }

    public void addToGcalendars(Gcalendar obj) {
        addToManyTarget("gcalendars", obj, true);
    }

    public void removeFromGcalendars(Gcalendar obj) {
        removeToManyTarget("gcalendars", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Gcalendar> getGcalendars() {
        return (List<Gcalendar>)readProperty("gcalendars");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "dateupdate":
                return this.dateupdate;
            case "descrizione":
                return this.descrizione;
            case "pwskey":
                return this.pwskey;
            case "agenti":
                return this.agenti;
            case "contatti":
                return this.contatti;
            case "gcalendars":
                return this.gcalendars;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "dateupdate":
                this.dateupdate = (LocalDateTime)val;
                break;
            case "descrizione":
                this.descrizione = (String)val;
                break;
            case "pwskey":
                this.pwskey = (String)val;
                break;
            case "agenti":
                this.agenti = val;
                break;
            case "contatti":
                this.contatti = val;
                break;
            case "gcalendars":
                this.gcalendars = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.dateupdate);
        out.writeObject(this.descrizione);
        out.writeObject(this.pwskey);
        out.writeObject(this.agenti);
        out.writeObject(this.contatti);
        out.writeObject(this.gcalendars);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.dateupdate = (LocalDateTime)in.readObject();
        this.descrizione = (String)in.readObject();
        this.pwskey = (String)in.readObject();
        this.agenti = in.readObject();
        this.contatti = in.readObject();
        this.gcalendars = in.readObject();
    }

}
