package winkhouse.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import winkhouse.orm.Agenti;
import winkhouse.orm.Ricerche;

/**
 * Class _Permessi was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Permessi extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODPERMESSO_PK_COLUMN = "CODPERMESSO";

    public static final Property<Boolean> CANREAD = Property.create("canread", Boolean.class);
    public static final Property<Boolean> CANWRITE = Property.create("canwrite", Boolean.class);
    public static final Property<LocalDateTime> DATEUPDATE = Property.create("dateupdate", LocalDateTime.class);
    public static final Property<String> DESCRIZIONE = Property.create("descrizione", String.class);
    public static final Property<Boolean> ISNOT = Property.create("isnot", Boolean.class);
    public static final Property<Agenti> AGENTI = Property.create("agenti", Agenti.class);
    public static final Property<Agenti> AGENTI1 = Property.create("agenti1", Agenti.class);
    public static final Property<Ricerche> RICERCHE = Property.create("ricerche", Ricerche.class);

    protected Boolean canread;
    protected Boolean canwrite;
    protected LocalDateTime dateupdate;
    protected String descrizione;
    protected Boolean isnot;

    protected Object agenti;
    protected Object agenti1;
    protected Object ricerche;

    public void setCanread(boolean canread) {
        beforePropertyWrite("canread", this.canread, canread);
        this.canread = canread;
    }

	public boolean isCanread() {
        beforePropertyRead("canread");
        if(this.canread == null) {
            return false;
        }
        return this.canread;
    }

    public void setCanwrite(boolean canwrite) {
        beforePropertyWrite("canwrite", this.canwrite, canwrite);
        this.canwrite = canwrite;
    }

	public boolean isCanwrite() {
        beforePropertyRead("canwrite");
        if(this.canwrite == null) {
            return false;
        }
        return this.canwrite;
    }

    public void setDateupdate(LocalDateTime dateupdate) {
        beforePropertyWrite("dateupdate", this.dateupdate, dateupdate);
        this.dateupdate = dateupdate;
    }

    public LocalDateTime getDateupdate() {
        beforePropertyRead("dateupdate");
        return this.dateupdate;
    }

    public void setDescrizione(String descrizione) {
        beforePropertyWrite("descrizione", this.descrizione, descrizione);
        this.descrizione = descrizione;
    }

    public String getDescrizione() {
        beforePropertyRead("descrizione");
        return this.descrizione;
    }

    public void setIsnot(boolean isnot) {
        beforePropertyWrite("isnot", this.isnot, isnot);
        this.isnot = isnot;
    }

	public boolean isIsnot() {
        beforePropertyRead("isnot");
        if(this.isnot == null) {
            return false;
        }
        return this.isnot;
    }

    public void setAgenti(Agenti agenti) {
        setToOneTarget("agenti", agenti, true);
    }

    public Agenti getAgenti() {
        return (Agenti)readProperty("agenti");
    }

    public void setAgenti1(Agenti agenti1) {
        setToOneTarget("agenti1", agenti1, true);
    }

    public Agenti getAgenti1() {
        return (Agenti)readProperty("agenti1");
    }

    public void setRicerche(Ricerche ricerche) {
        setToOneTarget("ricerche", ricerche, true);
    }

    public Ricerche getRicerche() {
        return (Ricerche)readProperty("ricerche");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "canread":
                return this.canread;
            case "canwrite":
                return this.canwrite;
            case "dateupdate":
                return this.dateupdate;
            case "descrizione":
                return this.descrizione;
            case "isnot":
                return this.isnot;
            case "agenti":
                return this.agenti;
            case "agenti1":
                return this.agenti1;
            case "ricerche":
                return this.ricerche;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "canread":
                this.canread = (Boolean)val;
                break;
            case "canwrite":
                this.canwrite = (Boolean)val;
                break;
            case "dateupdate":
                this.dateupdate = (LocalDateTime)val;
                break;
            case "descrizione":
                this.descrizione = (String)val;
                break;
            case "isnot":
                this.isnot = (Boolean)val;
                break;
            case "agenti":
                this.agenti = val;
                break;
            case "agenti1":
                this.agenti1 = val;
                break;
            case "ricerche":
                this.ricerche = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.canread);
        out.writeObject(this.canwrite);
        out.writeObject(this.dateupdate);
        out.writeObject(this.descrizione);
        out.writeObject(this.isnot);
        out.writeObject(this.agenti);
        out.writeObject(this.agenti1);
        out.writeObject(this.ricerche);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.canread = (Boolean)in.readObject();
        this.canwrite = (Boolean)in.readObject();
        this.dateupdate = (LocalDateTime)in.readObject();
        this.descrizione = (String)in.readObject();
        this.isnot = (Boolean)in.readObject();
        this.agenti = in.readObject();
        this.agenti1 = in.readObject();
        this.ricerche = in.readObject();
    }

}
