package winkhouse.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import winkhouse.orm.Agenti;
import winkhouse.orm.Colloquicriteriricerca;
import winkhouse.orm.Permessi;

/**
 * Class _Ricerche was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Ricerche extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODRICERCA_PK_COLUMN = "CODRICERCA";

    public static final Property<LocalDateTime> DATEUPDATE = Property.create("dateupdate", LocalDateTime.class);
    public static final Property<String> DESCRIZIONE = Property.create("descrizione", String.class);
    public static final Property<String> NOME = Property.create("nome", String.class);
    public static final Property<Integer> TIPO = Property.create("tipo", Integer.class);
    public static final Property<Agenti> AGENTI = Property.create("agenti", Agenti.class);
    public static final Property<List<Colloquicriteriricerca>> COLLOQUICRITERIRICERCAS = Property.create("colloquicriteriricercas", List.class);
    public static final Property<List<Permessi>> PERMESSIS = Property.create("permessis", List.class);

    protected LocalDateTime dateupdate;
    protected String descrizione;
    protected String nome;
    protected Integer tipo;

    protected Object agenti;
    protected Object colloquicriteriricercas;
    protected Object permessis;

    public void setDateupdate(LocalDateTime dateupdate) {
        beforePropertyWrite("dateupdate", this.dateupdate, dateupdate);
        this.dateupdate = dateupdate;
    }

    public LocalDateTime getDateupdate() {
        beforePropertyRead("dateupdate");
        return this.dateupdate;
    }

    public void setDescrizione(String descrizione) {
        beforePropertyWrite("descrizione", this.descrizione, descrizione);
        this.descrizione = descrizione;
    }

    public String getDescrizione() {
        beforePropertyRead("descrizione");
        return this.descrizione;
    }

    public void setNome(String nome) {
        beforePropertyWrite("nome", this.nome, nome);
        this.nome = nome;
    }

    public String getNome() {
        beforePropertyRead("nome");
        return this.nome;
    }

    public void setTipo(int tipo) {
        beforePropertyWrite("tipo", this.tipo, tipo);
        this.tipo = tipo;
    }

    public int getTipo() {
        beforePropertyRead("tipo");
        if(this.tipo == null) {
            return 0;
        }
        return this.tipo;
    }

    public void setAgenti(Agenti agenti) {
        setToOneTarget("agenti", agenti, true);
    }

    public Agenti getAgenti() {
        return (Agenti)readProperty("agenti");
    }

    public void addToColloquicriteriricercas(Colloquicriteriricerca obj) {
        addToManyTarget("colloquicriteriricercas", obj, true);
    }

    public void removeFromColloquicriteriricercas(Colloquicriteriricerca obj) {
        removeToManyTarget("colloquicriteriricercas", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Colloquicriteriricerca> getColloquicriteriricercas() {
        return (List<Colloquicriteriricerca>)readProperty("colloquicriteriricercas");
    }

    public void addToPermessis(Permessi obj) {
        addToManyTarget("permessis", obj, true);
    }

    public void removeFromPermessis(Permessi obj) {
        removeToManyTarget("permessis", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Permessi> getPermessis() {
        return (List<Permessi>)readProperty("permessis");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "dateupdate":
                return this.dateupdate;
            case "descrizione":
                return this.descrizione;
            case "nome":
                return this.nome;
            case "tipo":
                return this.tipo;
            case "agenti":
                return this.agenti;
            case "colloquicriteriricercas":
                return this.colloquicriteriricercas;
            case "permessis":
                return this.permessis;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "dateupdate":
                this.dateupdate = (LocalDateTime)val;
                break;
            case "descrizione":
                this.descrizione = (String)val;
                break;
            case "nome":
                this.nome = (String)val;
                break;
            case "tipo":
                this.tipo = (Integer)val;
                break;
            case "agenti":
                this.agenti = val;
                break;
            case "colloquicriteriricercas":
                this.colloquicriteriricercas = val;
                break;
            case "permessis":
                this.permessis = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.dateupdate);
        out.writeObject(this.descrizione);
        out.writeObject(this.nome);
        out.writeObject(this.tipo);
        out.writeObject(this.agenti);
        out.writeObject(this.colloquicriteriricercas);
        out.writeObject(this.permessis);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.dateupdate = (LocalDateTime)in.readObject();
        this.descrizione = (String)in.readObject();
        this.nome = (String)in.readObject();
        this.tipo = (Integer)in.readObject();
        this.agenti = in.readObject();
        this.colloquicriteriricercas = in.readObject();
        this.permessis = in.readObject();
    }

}
