package winkhouse.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Winksys was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Winksys extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String PROPERTYNAME_PK_COLUMN = "PROPERTYNAME";

    public static final Property<String> PROPERTYVALUE = Property.create("propertyvalue", String.class);

    protected String propertyvalue;


    public void setPropertyvalue(String propertyvalue) {
        beforePropertyWrite("propertyvalue", this.propertyvalue, propertyvalue);
        this.propertyvalue = propertyvalue;
    }

    public String getPropertyvalue() {
        beforePropertyRead("propertyvalue");
        return this.propertyvalue;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "propertyvalue":
                return this.propertyvalue;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "propertyvalue":
                this.propertyvalue = (String)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.propertyvalue);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.propertyvalue = (String)in.readObject();
    }

}
